paths:
  /mission:
    get:
      summary: Retrieve a list of missions
      tags:
        - Missions
      responses:
        '200':
          description: A list of missions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    storename:
                      type: string
                      example: 투썸플레이스사당역점
                    point:
                      type: string
                      example: 500p
                    storeTypes:
                      type: array
                      items:
                        type: string
                      example: ["중식", "일식", "한식", "양식", "동남아식"]
